version: "3"

volumes:
  data: {}

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/
    environment:
      - WANTEDLAB_DB_NAME=wantedlab
      - WANTEDLAB_DB_HOST=db
      - WANTEDLAB_DB_PORT=3306
    env_file:
      - env.deploy
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    command: >-
        sh -c 'python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000'
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=wantedlab
    env_file:
      - env.deploy
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - data:/var/lib/mysql
      - ./wantedlab.sql:/docker-entrypoint-initdb.d/dump.sql
